version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: UniSync
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "UniSuncPasswordH&H"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data:
  